services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
      args:
        - POETRY_HOME="/etc/poetry/"
    volumes:
      - ../.:/workspaces:cached
    command: sleep infinity
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: campio

  postgres-db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


volumes:
  postgres-data: {}
