FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update

# Install PostgreSQL
## Install psql command line tools
RUN apt-get install -y postgresql-client
RUN apt-get install -y libpq5

RUN git config --global --add safe.directory /workspaces
